name: digitallibrary
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  nb_utils: 6.1.0
  qr_flutter: 4.1.0
  flutter_zoom_drawer: 3.1.1
  http: 1.2.0
  get_storage: 2.1.1
  readmore: 2.2.0
  flutter_rating_bar: 4.0.1
  google_fonts: 6.1.0
  animated_splash_screen: 1.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/logoP.png
    - assets/images/logoH.png
    - assets/images/bg.png
    - assets/images/bg2.png
    - assets/images/bgL.png
    - assets/images/bgLL.png
    - assets/images/bgLLL.png
    - assets/images/cover.jpg
    - assets/images/cover2.jpeg
    - assets/images/cover3.jpeg
    - assets/images/garis.png
    - assets/images/profile.png
    - assets/images/list.png
    - assets/images/library.png
    - assets/images/home.png
    - assets/images/logout.png
  uses-material-design: true

